"""volta tabela tabela

Revision ID: 1aae5e93a97a
Revises: f20334f9e298
Create Date: 2024-05-21 14:01:55.509615

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel                                 # New


# revision identifiers, used by Alembic.
revision = '1aae5e93a97a'
down_revision = 'f20334f9e298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitação_tabela_especial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_inclusão', sa.DateTime(), nullable=False),
    sa.Column('nome_usuario', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email_usuario', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('geo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('comercial', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('operação', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cod_pdv', sa.Integer(), nullable=False),
    sa.Column('tabela', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ação', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('print_aprovação', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitação_tabela_especial')
    # ### end Alembic commands ###