"""nova tabela

Revision ID: a658c2d465a1
Revises: 3f7a25a85ef6
Create Date: 2024-05-21 13:55:47.267915

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel                                 # New


# revision identifiers, used by Alembic.
revision = 'a658c2d465a1'
down_revision = '3f7a25a85ef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###