"""exclui tabela

Revision ID: f20334f9e298
Revises: a658c2d465a1
Create Date: 2024-05-21 14:01:15.658511

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel                                 # New
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f20334f9e298'
down_revision = 'a658c2d465a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitação_tabela_especial')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitação_tabela_especial',
    sa.Column('data_inclusão', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('geo', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('comercial', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('operação', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cod_pdv', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tabela', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ação', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('print_aprovação', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email_usuario', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome_usuario', sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###